/*
 * Copyright 2026 MLorek
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.frostlake.metastore.model;

import java.time.Instant;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Represents a database SEQUENCE object
 */
public class Sequence {
    private final String name;
    private final AtomicLong currentValue;
    private final long startValue;
    private long increment;
    private final boolean order;
    private String comment;
    private final Instant createdTime = Instant.now();

    public Sequence(final String name, final long startValue, final long increment, final boolean order, final String comment) {
        this.name = name;
        this.startValue = startValue;
        this.increment = increment;
        this.order = order;
        this.currentValue = new AtomicLong(startValue - increment); // Start one before, so first NEXTVAL returns startValue
        this.comment = comment;
    }

    /**
     * Get the next value in the sequence (NEXTVAL)
     */
    public long nextVal() {
        return currentValue.addAndGet(increment);
    }

    /**
     * Get the current value of the sequence (CURRVAL)
     * Returns the last value generated by NEXTVAL
     */
    public long currVal() {
        final long current = currentValue.get();
        // If no NEXTVAL has been called yet, throw exception
        if (current == startValue - increment) {
            throw new RuntimeException("CURRVAL cannot be called before NEXTVAL for sequence: " + name);
        }
        return current;
    }

    /**
     * Get the current internal value (for cloning purposes)
     * This does not check if NEXTVAL was called
     */
    public long getCurrentValueRaw() {
        return currentValue.get();
    }

    /**
     * The value the NEXT call to {@link #nextVal()} will return, without consuming it — the
     * catalog's NEXT_VALUE. On a sequence nothing has drawn from yet this is its START value.
     */
    public long peekNextValue() {
        return currentValue.get() + increment;
    }

    /**
     * Set the current value (used by ALTER SEQUENCE)
     */
    public void setCurrentValue(final long value) {
        currentValue.set(value);
    }

    /** Owning role; defaults to SYSADMIN until stamped with the creating role at CREATE. */
    private String owner = "SYSADMIN";

    public String getName() {
        return name;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(final String owner) {
        this.owner = owner;
    }

    public long getStartValue() {
        return startValue;
    }

    public long getIncrement() {
        return increment;
    }

    /** Change the step applied by future NEXTVAL calls (ALTER SEQUENCE … SET INCREMENT). */
    public void setIncrement(final long increment) {
        this.increment = increment;
    }

    /** When this sequence was created, as SHOW SEQUENCES reports it. */
    public Instant getCreatedTime() {
        return createdTime;
    }

    public boolean isOrder() {
        return order;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(final String comment) {
        this.comment = comment;
    }

    public String getObjectType() {
        return "SEQUENCE";
    }

    @Override
    public String toString() {
        return "Sequence{" +
                "name='" + name + '\'' +
                ", currentValue=" + currentValue.get() +
                ", startValue=" + startValue +
                ", increment=" + increment +
                '}';
    }
}
